import { useState } from 'react'
import { getRaceConfig } from './supabase'
import LoginScreen from './LoginScreen'
import MapScreen from './MapScreen'
import ChallengesScreen from './ChallengesScreen'
import LeaderboardScreen from './LeaderboardScreen'
import ChatScreen from './ChatScreen'
import AdminScreen from './AdminScreen'
import BottomNav from './BottomNav'
